/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import API.Company;
import API.Person;
import API.Skill;
import Management.ManageData;
import Management.ManagePerson;
import java.text.ParseException;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
/**
 *
 * @author corentin
 */
public class AddPerson extends javax.swing.JPanel {
       private Company myCompany;
       private final JList<Person> myJlistPerson;
    /**
     * Creates new form addPerson
     * @param myCompany
     */
    public AddPerson(Company myCompany,JList<Person> myJlistPerson) {
        this.myCompany=myCompany;
        initComponents();
        this.myJlistPerson = myJlistPerson;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLeft = new javax.swing.JPanel();
        jFormattedTextFieldDatePerson = new javax.swing.JFormattedTextField();
        jTextFieldNomPerson = new javax.swing.JTextField();
        jTextFieldPrenomPerson = new javax.swing.JTextField();
        jLabelDateEPerson = new javax.swing.JLabel();
        jLabelPrenomPerson = new javax.swing.JLabel();
        jLabeNomPerson = new javax.swing.JLabel();
        jPanelRight = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DefaultListModel<Skill> modelMySkill = new DefaultListModel();
        jListMyskill = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        DefaultListModel<Skill> modelSkillAvailable = new DefaultListModel();
        jListAvailableSkill = new javax.swing.JList<>();
        jButtonShiftLeft = new javax.swing.JButton();
        jButtonShiftRight = new javax.swing.JButton();
        jPanelFooter = new javax.swing.JPanel();
        jButtonAddPerson = new javax.swing.JButton();

        setBackground(java.awt.Color.white);

        jPanelLeft.setBackground(java.awt.Color.white);

        jFormattedTextFieldDatePerson.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jFormattedTextFieldDatePerson.setToolTipText("");

        jLabelDateEPerson.setText("Date d'embauche :");

        jLabelPrenomPerson.setText("Prenom: ");

        jLabeNomPerson.setText("Nom :");

        javax.swing.GroupLayout jPanelLeftLayout = new javax.swing.GroupLayout(jPanelLeft);
        jPanelLeft.setLayout(jPanelLeftLayout);
        jPanelLeftLayout.setHorizontalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftLayout.createSequentialGroup()
                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLeftLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabeNomPerson)
                        .addGap(80, 80, 80))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLeftLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPrenomPerson)
                            .addComponent(jLabelDateEPerson))
                        .addGap(18, 18, 18)))
                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPrenomPerson)
                    .addComponent(jFormattedTextFieldDatePerson, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(jTextFieldNomPerson))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanelLeftLayout.setVerticalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeNomPerson)
                    .addComponent(jTextFieldNomPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrenomPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPrenomPerson))
                .addGap(34, 34, 34)
                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDateEPerson, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jFormattedTextFieldDatePerson, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanelRight.setBackground(java.awt.Color.white);

        jListMyskill.setModel(modelMySkill);
        jListMyskill.setCellRenderer(new SkillRenderer());
        Set entrySet = myCompany.listeSkill.entrySet();
        Iterator it = entrySet.iterator();
        while (it.hasNext()) {
            Map.Entry me = (Map.Entry)it.next();
            modelMySkill.addElement(myCompany.listeSkill.get(me.getKey()));

        }
        jScrollPane1.setViewportView(jListMyskill);

        jListAvailableSkill.setModel(modelSkillAvailable);
        jScrollPane2.setViewportView(jListAvailableSkill);
        jListAvailableSkill.setCellRenderer(new SkillRenderer());

        Set entrySetSAvailble = myCompany.listeSkill.entrySet();
        Iterator it2 = entrySetSAvailble.iterator();
        while (it2.hasNext()) {
            Map.Entry me2 = (Map.Entry)it2.next();
            modelSkillAvailable.addElement(myCompany.listeSkill.get(me2.getKey()));

        }

        jButtonShiftLeft.setText("<<");

        jButtonShiftRight.setText(">>");

        javax.swing.GroupLayout jPanelRightLayout = new javax.swing.GroupLayout(jPanelRight);
        jPanelRight.setLayout(jPanelRightLayout);
        jPanelRightLayout.setHorizontalGroup(
            jPanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRightLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonShiftLeft)
                    .addComponent(jButtonShiftRight))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
        );
        jPanelRightLayout.setVerticalGroup(
            jPanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addGap(0, 0, 0))
            .addGroup(jPanelRightLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonShiftLeft)
                .addGap(74, 74, 74)
                .addComponent(jButtonShiftRight)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelFooter.setBackground(java.awt.Color.white);

        jButtonAddPerson.setText("Valider");
        jButtonAddPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPersonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFooterLayout = new javax.swing.GroupLayout(jPanelFooter);
        jPanelFooter.setLayout(jPanelFooterLayout);
        jPanelFooterLayout.setHorizontalGroup(
            jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFooterLayout.createSequentialGroup()
                .addGap(361, 361, 361)
                .addComponent(jButtonAddPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        jPanelFooterLayout.setVerticalGroup(
            jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFooterLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jButtonAddPerson)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addComponent(jPanelFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPersonActionPerformed
    Person p = new Person();
    p.setFirstName(jTextFieldNomPerson.getText());
    p.setLastName(jTextFieldPrenomPerson.getText());
    p.setId(myCompany.listePerson.size()+1);
    try {
        p.setDateOfHire(jFormattedTextFieldDatePerson.getText());
    } catch (ParseException ex) {
        Logger.getLogger(AddPerson.class.getName()).log(Level.SEVERE, null, ex);
    }
    myCompany.addPerson(p);
     ManageData mPerson = new ManagePerson();
     mPerson.writeData(myCompany);
    }//GEN-LAST:event_jButtonAddPersonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddPerson;
    private javax.swing.JButton jButtonShiftLeft;
    private javax.swing.JButton jButtonShiftRight;
    private javax.swing.JFormattedTextField jFormattedTextFieldDatePerson;
    private javax.swing.JLabel jLabeNomPerson;
    private javax.swing.JLabel jLabelDateEPerson;
    private javax.swing.JLabel jLabelPrenomPerson;
    private javax.swing.JList<Skill> jListAvailableSkill;
    private javax.swing.JList<Skill> jListMyskill;
    private javax.swing.JPanel jPanelFooter;
    private javax.swing.JPanel jPanelLeft;
    private javax.swing.JPanel jPanelRight;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldNomPerson;
    private javax.swing.JTextField jTextFieldPrenomPerson;
    // End of variables declaration//GEN-END:variables
}
