/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static API.Company.listePerson;
import API.Person;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;
import javax.swing.DefaultListModel;

/**
 *
 * @author corentin
 */
public class ViewAllPerson extends javax.swing.JPanel {
    private MyFrame mf;
    /**
     * Creates new form ViewAllPerson
     */
    ViewAllPerson(MyFrame mf) {
        this.mf=mf;
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewAllPerson = new javax.swing.JPanel();
        EnteteAllPerson = new javax.swing.JPanel();
        labelAllPerson = new javax.swing.JLabel();
        corpAllPerson = new javax.swing.JPanel();
        jPanelListPerson = new javax.swing.JPanel();
        jPanelGoAddPerson = new javax.swing.JPanel();
        jLabelAdd = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DefaultListModel<Person> model = new DefaultListModel();
        jListPerson = new javax.swing.JList<>();
        jPanelCardInformation = new javax.swing.JPanel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelName = new javax.swing.JLabel();
        jTextFieldSurname = new javax.swing.JTextField();
        jLabelSurname = new javax.swing.JLabel();
        jFormattedTextFieldDate = new javax.swing.JFormattedTextField();
        jLabelDate = new javax.swing.JLabel();
        jPanelMyskill = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListSkill = new javax.swing.JList<>();

        setMinimumSize(new java.awt.Dimension(850, 700));
        setPreferredSize(new java.awt.Dimension(850, 700));

        viewAllPerson.setBackground(java.awt.Color.white);

        EnteteAllPerson.setBackground(new java.awt.Color(45, 118, 232));

        labelAllPerson.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        labelAllPerson.setForeground(java.awt.Color.white);
        labelAllPerson.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAllPerson.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/play-outlined-button-of-two-triangles.png"))); // NOI18N
        labelAllPerson.setText("Gestion du personnel");

        javax.swing.GroupLayout EnteteAllPersonLayout = new javax.swing.GroupLayout(EnteteAllPerson);
        EnteteAllPerson.setLayout(EnteteAllPersonLayout);
        EnteteAllPersonLayout.setHorizontalGroup(
            EnteteAllPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelAllPerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        EnteteAllPersonLayout.setVerticalGroup(
            EnteteAllPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelAllPerson, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
        );

        corpAllPerson.setBackground(java.awt.Color.white);

        jPanelGoAddPerson.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelGoAddPersonMouseClicked(evt);
            }
        });

        jLabelAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/icons8-plus-50.png"))); // NOI18N

        javax.swing.GroupLayout jPanelGoAddPersonLayout = new javax.swing.GroupLayout(jPanelGoAddPerson);
        jPanelGoAddPerson.setLayout(jPanelGoAddPersonLayout);
        jPanelGoAddPersonLayout.setHorizontalGroup(
            jPanelGoAddPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGoAddPersonLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        jPanelGoAddPersonLayout.setVerticalGroup(
            jPanelGoAddPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jListPerson.setModel(model);
        jListPerson.setCellRenderer(new personRenderer());
        Set entrySet = listePerson.entrySet();
        Iterator it = entrySet.iterator();
        while (it.hasNext()) {
            Map.Entry me = (Map.Entry)it.next();
            model.addElement(listePerson.get(me.getKey()));

        }
        jListPerson.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListPerson.setSelectionBackground(java.awt.Color.white);
        jListPerson.setValueIsAdjusting(true);
        jScrollPane1.setViewportView(jListPerson);

        javax.swing.GroupLayout jPanelListPersonLayout = new javax.swing.GroupLayout(jPanelListPerson);
        jPanelListPerson.setLayout(jPanelListPersonLayout);
        jPanelListPersonLayout.setHorizontalGroup(
            jPanelListPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListPersonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelGoAddPerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelListPersonLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanelListPersonLayout.setVerticalGroup(
            jPanelListPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListPersonLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jPanelGoAddPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabelName.setText("Nom");

        jLabelSurname.setText("Prenom");

        jFormattedTextFieldDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        jLabelDate.setText("Date d'embauche");

        javax.swing.GroupLayout jPanelCardInformationLayout = new javax.swing.GroupLayout(jPanelCardInformation);
        jPanelCardInformation.setLayout(jPanelCardInformationLayout);
        jPanelCardInformationLayout.setHorizontalGroup(
            jPanelCardInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCardInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCardInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSurname)
                    .addComponent(jLabelDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCardInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFormattedTextFieldDate)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addComponent(jTextFieldSurname))
                .addContainerGap())
        );
        jPanelCardInformationLayout.setVerticalGroup(
            jPanelCardInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCardInformationLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanelCardInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCardInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSurname))
                .addGap(18, 18, 18)
                .addGroup(jPanelCardInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jListSkill.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListSkill);

        javax.swing.GroupLayout jPanelMyskillLayout = new javax.swing.GroupLayout(jPanelMyskill);
        jPanelMyskill.setLayout(jPanelMyskillLayout);
        jPanelMyskillLayout.setHorizontalGroup(
            jPanelMyskillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMyskillLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanelMyskillLayout.setVerticalGroup(
            jPanelMyskillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMyskillLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout corpAllPersonLayout = new javax.swing.GroupLayout(corpAllPerson);
        corpAllPerson.setLayout(corpAllPersonLayout);
        corpAllPersonLayout.setHorizontalGroup(
            corpAllPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(corpAllPersonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelListPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jPanelCardInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22)
                .addComponent(jPanelMyskill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        corpAllPersonLayout.setVerticalGroup(
            corpAllPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(corpAllPersonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(corpAllPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelMyskill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelListPerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCardInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout viewAllPersonLayout = new javax.swing.GroupLayout(viewAllPerson);
        viewAllPerson.setLayout(viewAllPersonLayout);
        viewAllPersonLayout.setHorizontalGroup(
            viewAllPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EnteteAllPerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(corpAllPerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        viewAllPersonLayout.setVerticalGroup(
            viewAllPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewAllPersonLayout.createSequentialGroup()
                .addComponent(EnteteAllPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(corpAllPerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(viewAllPerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(viewAllPerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelGoAddPersonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelGoAddPersonMouseClicked
        
    }//GEN-LAST:event_jPanelGoAddPersonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EnteteAllPerson;
    private javax.swing.JPanel corpAllPerson;
    private javax.swing.JFormattedTextField jFormattedTextFieldDate;
    private javax.swing.JLabel jLabelAdd;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelSurname;
    private javax.swing.JList<Person> jListPerson;
    private javax.swing.JList<String> jListSkill;
    private javax.swing.JPanel jPanelCardInformation;
    private javax.swing.JPanel jPanelGoAddPerson;
    private javax.swing.JPanel jPanelListPerson;
    private javax.swing.JPanel jPanelMyskill;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldSurname;
    private javax.swing.JLabel labelAllPerson;
    private javax.swing.JPanel viewAllPerson;
    // End of variables declaration//GEN-END:variables
}
