/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Rectangle;

/**
 *
 * @author corentin
 */
public class ViewHome extends javax.swing.JPanel {

    /**
     * Creates new form Home
     */
    private MyFrame homeFrame;
    private SecondaryFrame mySecondFrame;
    ViewHome(MyFrame homeFrame) {
        this.homeFrame=homeFrame;
        mySecondFrame = new SecondaryFrame();
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ViewPrincipalHome = new javax.swing.JPanel();
        Corps = new javax.swing.JPanel();
        Cards = new javax.swing.JPanel();
        cardMission = new javax.swing.JPanel();
        imageCardMission = new javax.swing.JLabel();
        cardPerson = new javax.swing.JPanel();
        imageCardPerson = new javax.swing.JLabel();
        Entete = new javax.swing.JPanel();
        nameApplication = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(430, 500));

        ViewPrincipalHome.setBackground(new java.awt.Color(255, 255, 255));

        Corps.setBackground(java.awt.Color.white);

        Cards.setBackground(java.awt.Color.white);

        cardMission.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cardMissionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cardMissionMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cardMissionMouseReleased(evt);
            }
        });

        imageCardMission.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        imageCardMission.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageCardMission.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/icons8-tâche-filled-50.png"))); // NOI18N
        imageCardMission.setText("Gestion des missions");
        imageCardMission.setIconTextGap(8);

        javax.swing.GroupLayout cardMissionLayout = new javax.swing.GroupLayout(cardMission);
        cardMission.setLayout(cardMissionLayout);
        cardMissionLayout.setHorizontalGroup(
            cardMissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardMissionLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(imageCardMission, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        cardMissionLayout.setVerticalGroup(
            cardMissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardMissionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imageCardMission, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        cardPerson.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cardPersonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cardPersonMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cardPersonMouseReleased(evt);
            }
        });

        imageCardPerson.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        imageCardPerson.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageCardPerson.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/Contact_50px.png"))); // NOI18N
        imageCardPerson.setText("Gestion du personnel");
        imageCardPerson.setIconTextGap(8);

        javax.swing.GroupLayout cardPersonLayout = new javax.swing.GroupLayout(cardPerson);
        cardPerson.setLayout(cardPersonLayout);
        cardPersonLayout.setHorizontalGroup(
            cardPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardPersonLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(imageCardPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        cardPersonLayout.setVerticalGroup(
            cardPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPersonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageCardPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CardsLayout = new javax.swing.GroupLayout(Cards);
        Cards.setLayout(CardsLayout);
        CardsLayout.setHorizontalGroup(
            CardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(CardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cardPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardMission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CardsLayout.setVerticalGroup(
            CardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardsLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(cardMission, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(51, 51, 51)
                .addComponent(cardPerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CorpsLayout = new javax.swing.GroupLayout(Corps);
        Corps.setLayout(CorpsLayout);
        CorpsLayout.setHorizontalGroup(
            CorpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Cards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        CorpsLayout.setVerticalGroup(
            CorpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CorpsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Cards, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout ViewPrincipalHomeLayout = new javax.swing.GroupLayout(ViewPrincipalHome);
        ViewPrincipalHome.setLayout(ViewPrincipalHomeLayout);
        ViewPrincipalHomeLayout.setHorizontalGroup(
            ViewPrincipalHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Corps, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ViewPrincipalHomeLayout.setVerticalGroup(
            ViewPrincipalHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewPrincipalHomeLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Corps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        Entete.setBackground(new java.awt.Color(45, 118, 232));

        nameApplication.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        nameApplication.setForeground(java.awt.Color.white);
        nameApplication.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameApplication.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/play-outlined-button-of-two-triangles.png"))); // NOI18N
        nameApplication.setText("Gestionnaire");

        javax.swing.GroupLayout EnteteLayout = new javax.swing.GroupLayout(Entete);
        Entete.setLayout(EnteteLayout);
        EnteteLayout.setHorizontalGroup(
            EnteteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnteteLayout.createSequentialGroup()
                .addComponent(nameApplication, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        EnteteLayout.setVerticalGroup(
            EnteteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameApplication, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Entete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ViewPrincipalHome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Entete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ViewPrincipalHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cardMissionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardMissionMouseEntered
        evt.getComponent().setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_cardMissionMouseEntered

    private void cardMissionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardMissionMouseExited
        evt.getComponent().setBackground(new Color(224, 224, 224));
    }//GEN-LAST:event_cardMissionMouseExited

    private void cardPersonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardPersonMouseEntered
        evt.getComponent().setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_cardPersonMouseEntered

    private void cardPersonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardPersonMouseExited
        evt.getComponent().setBackground(new Color(224, 224, 224));
    }//GEN-LAST:event_cardPersonMouseExited

    private void cardMissionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardMissionMouseReleased
         //Decoupage de l'écran en deux parties   
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice defaultScreen = ge.getDefaultScreenDevice();
        Rectangle rect = defaultScreen.getDefaultConfiguration().getBounds();
        mySecondFrame.setMinimumSize(new Dimension((int)(rect.width)*2/3,700));
        int x = (int) rect.getMaxX() - mySecondFrame.getWidth();
        int y = 0;
        //On position la nouvelle fenetre en haut à droite
        mySecondFrame.setLocation(x,y);
        // On supprime la vue ViewAllPerson si il est visible
        if(homeFrame.vallp.isVisible()){
            mySecondFrame.remove(homeFrame.vallp);
        }
        mySecondFrame.add(homeFrame.vallm);
        mySecondFrame.repaint();
        mySecondFrame.setVisible(true);
    }//GEN-LAST:event_cardMissionMouseReleased

    private void cardPersonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardPersonMouseReleased
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            GraphicsDevice defaultScreen = ge.getDefaultScreenDevice();
            Rectangle rect = defaultScreen.getDefaultConfiguration().getBounds();
            mySecondFrame.setMinimumSize(new Dimension((int)(rect.width)*2/3,700));
            int x = (int) rect.getMaxX() - mySecondFrame.getWidth();
            int y = 0;
            mySecondFrame.setLocation(x,y);
            if(homeFrame.vallp.isVisible()){
                mySecondFrame.remove(homeFrame.vallm);
            }
            mySecondFrame.add(homeFrame.vallp);
            mySecondFrame.repaint();
            mySecondFrame.setVisible(true);
    }//GEN-LAST:event_cardPersonMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cards;
    private javax.swing.JPanel Corps;
    private javax.swing.JPanel Entete;
    private javax.swing.JPanel ViewPrincipalHome;
    private javax.swing.JPanel cardMission;
    private javax.swing.JPanel cardPerson;
    private javax.swing.JLabel imageCardMission;
    private javax.swing.JLabel imageCardPerson;
    private javax.swing.JLabel nameApplication;
    // End of variables declaration//GEN-END:variables
}
