/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.NouvelleInterface;

import API.Company;
import Management.ManageData;
import Management.ManageMission;
import Management.ManagePerson;
import Management.ManageSkill;
import javax.swing.JFrame;

/**
 *
 * @author MathieuSTIVANIN
 */
public class home extends javax.swing.JFrame {
    Company myCompany;
    /**
     * Creates new form myFrame
     */
    public home() {
        loadData();
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        jLabelReturn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHeader = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelReturn = new javax.swing.JLabel();
        jLabelAdd = new javax.swing.JLabel();
        jPanelContainer = new javax.swing.JPanel();
        jPanelMenuLeft = new javax.swing.JPanel();
        jPanelMenuPerson = new javax.swing.JPanel();
        jLabelPerson = new javax.swing.JLabel();
        jPanelMenuMission = new javax.swing.JPanel();
        jLabelMission = new javax.swing.JLabel();
        jPanelLogo = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Arès");

        jPanelHeader.setBackground(new java.awt.Color(255, 255, 255));

        jLabelTitle.setFont(new java.awt.Font("Roboto", 0, 40));
        jLabelTitle.setForeground(new java.awt.Color(48, 51, 58));
        jLabelTitle.setText("Accueil");

        jLabelReturn.setFont(new java.awt.Font("Roboto", 0, 20));
        jLabelReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/ic_arrow_back_black_48dp.png"))); // NOI18N
        jLabelReturn.setText("Retours");

        jLabelAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/ic_add_circle_black_24dp.png"))); // NOI18N
        jLabelAdd.setText("Ajouter");

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelReturn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(122, 122, 122)
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addComponent(jLabelAdd)
                .addGap(41, 41, 41))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitle)
                    .addComponent(jLabelReturn)
                    .addComponent(jLabelAdd))
                .addContainerGap())
        );

        jPanelContainer.setBackground(new java.awt.Color(246, 246, 246));
        jPanelContainer.setLayout(new java.awt.CardLayout());

        jPanelMenuLeft.setBackground(new java.awt.Color(49, 51, 66));

        jPanelMenuPerson.setBackground(new java.awt.Color(49, 51, 66));
        jPanelMenuPerson.setForeground(new java.awt.Color(255, 255, 255));
        jPanelMenuPerson.setToolTipText("");
        jPanelMenuPerson.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jPanelMenuPerson.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanelMenuPersonMouseReleased(evt);
            }
        });

        jLabelPerson.setFont(new java.awt.Font("Roboto", 0, 19));
        jLabelPerson.setForeground(new java.awt.Color(153, 156, 163));
        jLabelPerson.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/person_icon.png"))); // NOI18N
        jLabelPerson.setIconTextGap(15);
        jLabelPerson.setText("Personnes");
        jLabelPerson.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelPersonMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuPersonLayout = new javax.swing.GroupLayout(jPanelMenuPerson);
        jPanelMenuPerson.setLayout(jPanelMenuPersonLayout);
        jPanelMenuPersonLayout.setHorizontalGroup(
            jPanelMenuPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuPersonLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabelPerson)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMenuPersonLayout.setVerticalGroup(
            jPanelMenuPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuPersonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPerson, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelMenuMission.setBackground(new java.awt.Color(49, 51, 66));
        jPanelMenuMission.setForeground(new java.awt.Color(102, 102, 102));
        jPanelMenuMission.setPreferredSize(new java.awt.Dimension(163, 84));
        jPanelMenuMission.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanelMenuMissionMouseReleased(evt);
            }
        });

        jLabelMission.setFont(new java.awt.Font("Roboto", 0, 19));
        jLabelMission.setForeground(new java.awt.Color(153, 156, 163));
        jLabelMission.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/mission_icon.png"))); // NOI18N
        jLabelMission.setIconTextGap(15);
        jLabelMission.setText("Missions");
        jLabelMission.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelMissionMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuMissionLayout = new javax.swing.GroupLayout(jPanelMenuMission);
        jPanelMenuMission.setLayout(jPanelMenuMissionLayout);
        jPanelMenuMissionLayout.setHorizontalGroup(
            jPanelMenuMissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuMissionLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabelMission)
                .addGap(64, 64, 64))
        );
        jPanelMenuMissionLayout.setVerticalGroup(
            jPanelMenuMissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuMissionLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabelMission)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanelLogo.setBackground(new java.awt.Color(49, 51, 66));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/logoPetitTaille.png"))); // NOI18N
        jLabelLogo.setToolTipText("");
        jLabelLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelLogoMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelLogoLayout = new javax.swing.GroupLayout(jPanelLogo);
        jPanelLogo.setLayout(jPanelLogoLayout);
        jPanelLogoLayout.setHorizontalGroup(
            jPanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLogoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        jPanelLogoLayout.setVerticalGroup(
            jPanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLogoLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabelLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelMenuLeftLayout = new javax.swing.GroupLayout(jPanelMenuLeft);
        jPanelMenuLeft.setLayout(jPanelMenuLeftLayout);
        jPanelMenuLeftLayout.setHorizontalGroup(
            jPanelMenuLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenuPerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelMenuMission, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
            .addComponent(jPanelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelMenuLeftLayout.setVerticalGroup(
            jPanelMenuLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLeftLayout.createSequentialGroup()
                .addComponent(jPanelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPanelMenuPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelMenuMission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelMenuLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanelMenuLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelPersonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPersonMouseReleased
        jPanelContainer.removeAll();
        jPanelContainer.add(new PersonList(myCompany));
        jPanelContainer.repaint();
        jPanelContainer.revalidate();
        jLabelReturn.setVisible(true);
        jLabelTitle.setText("Liste des Personnes");
        jPanelMenuPerson.setBackground(new java.awt.Color(30, 32, 44));
        jLabelPerson.setForeground(new java.awt.Color(254,254,254));
        jPanelMenuMission.setBackground(new java.awt.Color(49,51,66));
        jLabelMission.setForeground(new java.awt.Color(153, 156, 163));
    }//GEN-LAST:event_jLabelPersonMouseReleased

    private void jPanelMenuPersonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMenuPersonMouseReleased
        jPanelContainer.removeAll();
        jPanelContainer.add(new PersonList(myCompany));
        jPanelContainer.repaint();
        jPanelContainer.revalidate();
        jLabelReturn.setVisible(true);
        jLabelTitle.setText("Liste des Personnes");
        jPanelMenuPerson.setBackground(new java.awt.Color(30, 32, 44));
        jLabelPerson.setForeground(new java.awt.Color(254,254,254));
        jPanelMenuMission.setBackground(new java.awt.Color(49,51,66));
        jLabelMission.setForeground(new java.awt.Color(153, 156, 163));
    }//GEN-LAST:event_jPanelMenuPersonMouseReleased

    private void jLabelMissionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMissionMouseReleased
        jPanelContainer.removeAll();
        jPanelContainer.add(new MissionList(myCompany,this));
        jPanelContainer.repaint();
        jPanelContainer.revalidate();
        jLabelReturn.setVisible(true);
        jLabelTitle.setText("Liste des Missions");
        jPanelMenuMission.setBackground(new java.awt.Color(30, 32, 44));
        jLabelMission.setForeground(new java.awt.Color(254,254,254));
        jPanelMenuPerson.setBackground(new java.awt.Color(49,51,66));
        jLabelPerson.setForeground(new java.awt.Color(153, 156, 163));
    }//GEN-LAST:event_jLabelMissionMouseReleased

    private void jPanelMenuMissionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMenuMissionMouseReleased
        jPanelContainer.removeAll();
        jPanelContainer.add(new MissionList(myCompany,this));
        jPanelContainer.repaint();
        jPanelContainer.revalidate();
        jLabelReturn.setVisible(true);
        jLabelTitle.setText("Liste des Missions");
        jPanelMenuMission.setBackground(new java.awt.Color(30, 32, 44));
        jLabelMission.setForeground(new java.awt.Color(254,254,254));
        jPanelMenuPerson.setBackground(new java.awt.Color(49,51,66));
        jLabelPerson.setForeground(new java.awt.Color(153, 156, 163));
    }//GEN-LAST:event_jPanelMenuMissionMouseReleased

    private void jLabelLogoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogoMouseReleased
        jPanelContainer.removeAll();
        jPanelContainer.repaint();
        jPanelContainer.revalidate();
        jLabelReturn.setVisible(false);
        jLabelTitle.setText("Accueil");
    }//GEN-LAST:event_jLabelLogoMouseReleased
    
    
    private void loadData() {
        this.myCompany = new Company("Arès");
        //Recharger les competences 
        ManageData mySkill = new ManageSkill();
        mySkill.readData(myCompany);
        
        //Recharger les personnes en premier
        ManageData mPerson = new ManagePerson();
        mPerson.readData(myCompany);
        //myCompany.displayPerson();


        //myCompany.displaySkills();

        // Réafecter tous les projets aux bonnes personnes
        ManageData mMission = new ManageMission();
        mMission.readData(myCompany);
        //myCompany.displayMissions();
        //myCompany.displayPerson();

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAdd;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelMission;
    private javax.swing.JLabel jLabelPerson;
    private javax.swing.JLabel jLabelReturn;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    protected javax.swing.JPanel jPanelContainer;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelLogo;
    private javax.swing.JPanel jPanelMenuLeft;
    private javax.swing.JPanel jPanelMenuMission;
    private javax.swing.JPanel jPanelMenuPerson;
    // End of variables declaration//GEN-END:variables
}
