/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.NouvelleInterface;

import API.Company;
import API.Mission;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author corentin
 */
public class MissionList extends javax.swing.JPanel {

   

    /**
     * Creates new form MissionList
     */
    Company myCompany;
    home myFrame;
    public MissionList(Company myCompany,home myFrame) {
        this.myFrame=myFrame;
        this.myCompany=myCompany;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHeader = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelReturn = new javax.swing.JLabel();
        jLabelAdd = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        List<Mission> MissionList = new ArrayList<Mission>(myCompany.listeMission.values());
        jTableMission = new javax.swing.JTable();

        setBackground(new java.awt.Color(246, 246, 246));

        jPanelHeader.setBackground(new java.awt.Color(255, 255, 255));

        jLabelTitle.setFont(new java.awt.Font("Roboto", 0, 40));
        jLabelTitle.setForeground(new java.awt.Color(48, 51, 58));
        jLabelTitle.setText("Accueil");

        jLabelReturn.setFont(new java.awt.Font("Roboto", 0, 20));
        jLabelReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/ic_arrow_back_black_48dp.png"))); // NOI18N
        jLabelReturn.setText("Retours");

        jLabelAdd.setBackground(java.awt.Color.lightGray);
        jLabelAdd.setFont(new java.awt.Font("Roboto", 0, 20));
        jLabelAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/ic_add_circle_black_24dp.png"))); // NOI18N
        jLabelAdd.setText("Ajouter");

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelReturn, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                .addComponent(jLabelAdd)
                .addGap(41, 41, 41))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitle)
                    .addComponent(jLabelReturn)
                    .addComponent(jLabelAdd))
                .addContainerGap())
        );

        jScrollPane1.setWheelScrollingEnabled(false);

        MissionTableModel modelMission = new MissionTableModel(MissionList);
        jTableMission.setModel(modelMission);
        jTableMission.setAutoCreateRowSorter(true);
        ProgressCellRenderer pcr = new ProgressCellRenderer();
        TableColumnModel tcm = jTableMission.getColumnModel();
        tcm.getColumn(3).setCellRenderer(pcr);
        jTableMission.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMissionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMission);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTableMissionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMissionMouseClicked
        MissionTableModel model = (MissionTableModel)jTableMission.getModel();
        int row = jTableMission.getSelectedRow();
        int col = jTableMission.columnAtPoint(evt.getPoint());
        
        
        if(col == 4) { //Click sur Details 
             Mission missionSelected = model.missionList.get(row);
             MissionDetail md = new MissionDetail(missionSelected);
             myFrame.jPanelContainer.removeAll();
             myFrame.jPanelContainer.add(md);
             myFrame.repaint();
             myFrame.revalidate();
        }
        
    }//GEN-LAST:event_jTableMissionMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAdd;
    private javax.swing.JLabel jLabelReturn;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMission;
    // End of variables declaration//GEN-END:variables
}
