/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.NouvelleInterface;

import API.Company;
import API.Mission;
import java.awt.Point;
import java.util.ArrayList;
import java.util.List;
import javax.swing.RowSorter;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;
import static jdk.nashorn.internal.objects.NativeArray.map;

/**
 *
 * @author corentin
 */
public class MissionList extends javax.swing.JPanel {

   

    /**
     * Creates new form MissionList
     */
    Company myCompany;
    public MissionList(Company myCompany) {
        this.myCompany=myCompany;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        List<Mission> MissionList = new ArrayList<Mission>(myCompany.listeMission.values());
        jTableMission = new javax.swing.JTable();

        setBackground(new java.awt.Color(246, 246, 246));

        jScrollPane1.setWheelScrollingEnabled(false);

        MissionTableModel modelMission = new MissionTableModel(MissionList);
        jTableMission.setModel(modelMission);
        jTableMission.setAutoCreateRowSorter(true);
        ProgressCellRenderer pcr = new ProgressCellRenderer();
        TableColumnModel tcm = jTableMission.getColumnModel();
        tcm.getColumn(4).setCellRenderer(pcr);
        jTableMission.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMissionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMission);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTableMissionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMissionMouseClicked
        MissionTableModel model = (MissionTableModel)jTableMission.getModel();
        int row = jTableMission.getSelectedRow();
        int col = jTableMission.columnAtPoint(evt.getPoint());
        
        Mission missionSelected = model.missionList.get(row);
        System.out.println(missionSelected.toString());
    }//GEN-LAST:event_jTableMissionMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMission;
    // End of variables declaration//GEN-END:variables
}
