/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.NouvelleInterface;

import API.Company;
import API.Person;
import java.util.ArrayList;

/**
 *
 * @author corentin
 */
public class PersonList extends javax.swing.JPanel {

    /**
     * Creates new form PersonList
     */
    Company myCompany;
    public PersonList(Company myCompany) {
        this.myCompany=myCompany;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ArrayList<Person> PersonList = new ArrayList<Person>(myCompany.listePerson.values());
        jTablePerson = new javax.swing.JTable();

        setBackground(new java.awt.Color(246, 246, 246));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 402));

        PersonTableModel modelPerson = new PersonTableModel(PersonList);
        jTablePerson.setModel(modelPerson);
        jTablePerson.setAutoCreateRowSorter(true);
        jScrollPane1.setViewportView(jTablePerson);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePerson;
    // End of variables declaration//GEN-END:variables
}
