/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author corentin
 */
public class ViewAllMission extends javax.swing.JPanel {

    /**
     * Creates new form ViewAllMission
     */
    public ViewAllMission() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewAllMission = new javax.swing.JPanel();
        EnteteAllMission = new javax.swing.JPanel();
        labelAllMission = new javax.swing.JLabel();
        corpsAllMission = new javax.swing.JPanel();
        jPanelListMission = new javax.swing.JPanel();
        jPanelGoAddMission = new javax.swing.JPanel();
        jLabelAddMission = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListMission = new javax.swing.JList<>();
        jPanelCardInformationMission = new javax.swing.JPanel();
        jTextFieldName1 = new javax.swing.JTextField();
        jLabelName1 = new javax.swing.JLabel();
        jTextFieldSurname1 = new javax.swing.JTextField();
        jLabelSurname1 = new javax.swing.JLabel();
        jFormattedTextFieldDate1 = new javax.swing.JFormattedTextField();
        jLabelDate1 = new javax.swing.JLabel();
        jLabelDate2 = new javax.swing.JLabel();
        jFormattedTextFieldDate2 = new javax.swing.JFormattedTextField();
        jPanelRequirements = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListRequirements = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();

        viewAllMission.setBackground(java.awt.Color.white);

        EnteteAllMission.setBackground(new java.awt.Color(45, 118, 232));

        labelAllMission.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        labelAllMission.setForeground(java.awt.Color.white);
        labelAllMission.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAllMission.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/play-outlined-button-of-two-triangles.png"))); // NOI18N
        labelAllMission.setText("Gestion des missions");

        javax.swing.GroupLayout EnteteAllMissionLayout = new javax.swing.GroupLayout(EnteteAllMission);
        EnteteAllMission.setLayout(EnteteAllMissionLayout);
        EnteteAllMissionLayout.setHorizontalGroup(
            EnteteAllMissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelAllMission, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        EnteteAllMissionLayout.setVerticalGroup(
            EnteteAllMissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelAllMission, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
        );

        corpsAllMission.setBackground(java.awt.Color.white);

        jPanelGoAddMission.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelGoAddMissionMouseClicked(evt);
            }
        });

        jLabelAddMission.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAddMission.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/icons8-plus-50.png"))); // NOI18N

        javax.swing.GroupLayout jPanelGoAddMissionLayout = new javax.swing.GroupLayout(jPanelGoAddMission);
        jPanelGoAddMission.setLayout(jPanelGoAddMissionLayout);
        jPanelGoAddMissionLayout.setHorizontalGroup(
            jPanelGoAddMissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGoAddMissionLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelAddMission, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        jPanelGoAddMissionLayout.setVerticalGroup(
            jPanelGoAddMissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelAddMission, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jListMission.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(jListMission);

        javax.swing.GroupLayout jPanelListMissionLayout = new javax.swing.GroupLayout(jPanelListMission);
        jPanelListMission.setLayout(jPanelListMissionLayout);
        jPanelListMissionLayout.setHorizontalGroup(
            jPanelListMissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListMissionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelGoAddMission, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelListMissionLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanelListMissionLayout.setVerticalGroup(
            jPanelListMissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListMissionLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addGap(13, 13, 13)
                .addComponent(jPanelGoAddMission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabelName1.setText("Nom");

        jLabelSurname1.setText("Date de début");

        jFormattedTextFieldDate1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        jLabelDate1.setText("Durée");

        jLabelDate2.setText("Etat");

        jFormattedTextFieldDate2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        javax.swing.GroupLayout jPanelCardInformationMissionLayout = new javax.swing.GroupLayout(jPanelCardInformationMission);
        jPanelCardInformationMission.setLayout(jPanelCardInformationMissionLayout);
        jPanelCardInformationMissionLayout.setHorizontalGroup(
            jPanelCardInformationMissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCardInformationMissionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCardInformationMissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelName1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSurname1)
                    .addComponent(jLabelDate1)
                    .addComponent(jLabelDate2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCardInformationMissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFormattedTextFieldDate2)
                    .addComponent(jFormattedTextFieldDate1)
                    .addComponent(jTextFieldName1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(jTextFieldSurname1))
                .addContainerGap())
        );
        jPanelCardInformationMissionLayout.setVerticalGroup(
            jPanelCardInformationMissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCardInformationMissionLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanelCardInformationMissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldName1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelName1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCardInformationMissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSurname1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSurname1))
                .addGap(18, 18, 18)
                .addGroup(jPanelCardInformationMissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDate1))
                .addGap(18, 18, 18)
                .addGroup(jPanelCardInformationMissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDate2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jListRequirements.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jListRequirements);

        javax.swing.GroupLayout jPanelRequirementsLayout = new javax.swing.GroupLayout(jPanelRequirements);
        jPanelRequirements.setLayout(jPanelRequirementsLayout);
        jPanelRequirementsLayout.setHorizontalGroup(
            jPanelRequirementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRequirementsLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanelRequirementsLayout.setVerticalGroup(
            jPanelRequirementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRequirementsLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addGap(74, 74, 74))
        );

        jButton1.setText("< Retour");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout corpsAllMissionLayout = new javax.swing.GroupLayout(corpsAllMission);
        corpsAllMission.setLayout(corpsAllMissionLayout);
        corpsAllMissionLayout.setHorizontalGroup(
            corpsAllMissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(corpsAllMissionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(corpsAllMissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(corpsAllMissionLayout.createSequentialGroup()
                        .addComponent(jPanelListMission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jPanelCardInformationMission, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(22, 22, 22)
                        .addComponent(jPanelRequirements, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(corpsAllMissionLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        corpsAllMissionLayout.setVerticalGroup(
            corpsAllMissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(corpsAllMissionLayout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(corpsAllMissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelRequirements, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelListMission, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCardInformationMission, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout viewAllMissionLayout = new javax.swing.GroupLayout(viewAllMission);
        viewAllMission.setLayout(viewAllMissionLayout);
        viewAllMissionLayout.setHorizontalGroup(
            viewAllMissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EnteteAllMission, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(corpsAllMission, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        viewAllMissionLayout.setVerticalGroup(
            viewAllMissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewAllMissionLayout.createSequentialGroup()
                .addComponent(EnteteAllMission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(corpsAllMission, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 733, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(viewAllMission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(viewAllMission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelGoAddMissionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelGoAddMissionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelGoAddMissionMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EnteteAllMission;
    private javax.swing.JPanel corpsAllMission;
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFormattedTextFieldDate1;
    private javax.swing.JFormattedTextField jFormattedTextFieldDate2;
    private javax.swing.JLabel jLabelAddMission;
    private javax.swing.JLabel jLabelDate1;
    private javax.swing.JLabel jLabelDate2;
    private javax.swing.JLabel jLabelName1;
    private javax.swing.JLabel jLabelSurname1;
    private javax.swing.JList<String> jListMission;
    private javax.swing.JList<String> jListRequirements;
    private javax.swing.JPanel jPanelCardInformationMission;
    private javax.swing.JPanel jPanelGoAddMission;
    private javax.swing.JPanel jPanelListMission;
    private javax.swing.JPanel jPanelRequirements;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextFieldName1;
    private javax.swing.JTextField jTextFieldSurname1;
    private javax.swing.JLabel labelAllMission;
    private javax.swing.JPanel viewAllMission;
    // End of variables declaration//GEN-END:variables
}
